# Numpy Variables

Start working with numpy and initialize it

**Note:** So basically numpy is a list or an array

In [1]:
import numpy as np

## Creating Numpy Arrays

Creating numpy array with python list

In [2]:
my_list = [1, 2, 3, 4, 5]

my_list

[1, 2, 3, 4, 5]

In [3]:
my_list = np.array(my_list)

In [4]:
my_list.shape

(5,)

In [5]:
my_list_matrix = np.array([[1, 2], [3, 4]]) 

my_list_matrix

array([[1, 2],
       [3, 4]])

In [6]:
my_list_matrix.shape

(2, 2)

In [7]:
my_list_dimension = np.array([1, 2, 3, 4, 5], ndmin = 2)

my_list_dimension

array([[1, 2, 3, 4, 5]])

In [8]:
my_list_dimension.shape

(1, 5)

## Creating Numpy Arrays

Creating numpy array with python list

## Built in Methods

Heres some method to build numpy:
+ arange
+ zeros and ones
+ linspace
+ eye
+ random.rand
+ random.randint

And here's all of the example process:

In [9]:
my_matrix = [[1, 2, 3],[4, 5, 6],[7, 8, 9]]

my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

### arange

Create matrix or array with numpy

In [10]:
matrix = np.array(my_matrix)

matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
np.arange(0, 11, 2)

array([ 0,  2,  4,  6,  8, 10])

But `numpy.arrange` can't be used to generate 2D array, better to use `numpy.concatenate`. Here's the example:

- **Example 1**

In [13]:
matrix_2d = [[np.arange(0, 5)], [np.arange(10, 15)], [np.arange(20, 25)]]

matrix_2d

[[array([0, 1, 2, 3, 4])],
 [array([10, 11, 12, 13, 14])],
 [array([20, 21, 22, 23, 24])]]

In [14]:
matrix = np.array(matrix_2d)

matrix

array([[[ 0,  1,  2,  3,  4]],

       [[10, 11, 12, 13, 14]],

       [[20, 21, 22, 23, 24]]])

In [15]:
matrix.shape

(3, 1, 5)

- **Example 2**

In [16]:
matrix_2d = [np.arange(0, 5)], [np.arange(10, 15)], [np.arange(20, 25)]

matrix_2d

([array([0, 1, 2, 3, 4])],
 [array([10, 11, 12, 13, 14])],
 [array([20, 21, 22, 23, 24])])

In [17]:
matrix = np.array(matrix_2d)

matrix

array([[[ 0,  1,  2,  3,  4]],

       [[10, 11, 12, 13, 14]],

       [[20, 21, 22, 23, 24]]])

In [18]:
matrix.shape

(3, 1, 5)

### zeros, ones and full

Here's the explanation about that function:
+ `zeros` create an numpy array with "0" as initial value, 
+ `ones` uses "1" as initial value.
+ `full` uses custom value as initial the value.

In [19]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [20]:
print(np.zeros(5))

[0. 0. 0. 0. 0.]


In [21]:
np.zeros((5, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [22]:
np.zeros((5, 1))

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.]])

In [23]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [24]:
np.ones((5, 5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [25]:
np.ones((5, 1))

array([[1.],
       [1.],
       [1.],
       [1.],
       [1.]])

In [26]:
np.full(5, 10)

array([10, 10, 10, 10, 10])

In [27]:
np.full((5, 5), 2)

array([[2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2]])

In [28]:
np.full((5, 1), 2)

array([[2],
       [2],
       [2],
       [2],
       [2]])

### linspace

Linspace uses to create matrix with initial value which have range number in it's function.

In [29]:
np.linspace(-30, 30, 60)

array([-30.        , -28.98305085, -27.96610169, -26.94915254,
       -25.93220339, -24.91525424, -23.89830508, -22.88135593,
       -21.86440678, -20.84745763, -19.83050847, -18.81355932,
       -17.79661017, -16.77966102, -15.76271186, -14.74576271,
       -13.72881356, -12.71186441, -11.69491525, -10.6779661 ,
        -9.66101695,  -8.6440678 ,  -7.62711864,  -6.61016949,
        -5.59322034,  -4.57627119,  -3.55932203,  -2.54237288,
        -1.52542373,  -0.50847458,   0.50847458,   1.52542373,
         2.54237288,   3.55932203,   4.57627119,   5.59322034,
         6.61016949,   7.62711864,   8.6440678 ,   9.66101695,
        10.6779661 ,  11.69491525,  12.71186441,  13.72881356,
        14.74576271,  15.76271186,  16.77966102,  17.79661017,
        18.81355932,  19.83050847,  20.84745763,  21.86440678,
        22.88135593,  23.89830508,  24.91525424,  25.93220339,
        26.94915254,  27.96610169,  28.98305085,  30.        ])

In [30]:
np.linspace(0, 10, 30)

array([ 0.        ,  0.34482759,  0.68965517,  1.03448276,  1.37931034,
        1.72413793,  2.06896552,  2.4137931 ,  2.75862069,  3.10344828,
        3.44827586,  3.79310345,  4.13793103,  4.48275862,  4.82758621,
        5.17241379,  5.51724138,  5.86206897,  6.20689655,  6.55172414,
        6.89655172,  7.24137931,  7.5862069 ,  7.93103448,  8.27586207,
        8.62068966,  8.96551724,  9.31034483,  9.65517241, 10.        ])

In [31]:
# numpy.linespace(start, end, number of rows)
np.linspace((1, 2, 3),(10, 20, 30), 5)

array([[ 1.  ,  2.  ,  3.  ],
       [ 3.25,  6.5 ,  9.75],
       [ 5.5 , 11.  , 16.5 ],
       [ 7.75, 15.5 , 23.25],
       [10.  , 20.  , 30.  ]])

In [32]:
# numpy.linespace(start, end, number of rows)
np.linspace((1, 2),(10, 20), 5)

array([[ 1.  ,  2.  ],
       [ 3.25,  6.5 ],
       [ 5.5 , 11.  ],
       [ 7.75, 15.5 ],
       [10.  , 20.  ]])

### eye

Create an matrix from input dimension with the pattern like this

In [33]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

### random.rand

In [34]:
np.random.rand(2)

array([0.61411727, 0.58440406])

In [35]:
np.random.rand(5, 5)

array([[0.16024795, 0.77210677, 0.50076428, 0.15831649, 0.4109203 ],
       [0.57966883, 0.14247046, 0.7688213 , 0.63419614, 0.17391277],
       [0.8700997 , 0.13984439, 0.23254583, 0.02554353, 0.70250903],
       [0.45041419, 0.12361243, 0.41496153, 0.58570935, 0.31119741],
       [0.95080136, 0.33931429, 0.12832064, 0.37566072, 0.95393378]])

### random.randn

Create two dimension array with random values

In [36]:
np.random.randn(2)

array([0.84350975, 0.25478951])

In [37]:
np.random.randn(5, 5)

array([[ 1.18551756,  0.88236944,  0.11307611, -0.97183883, -0.85796084],
       [-0.44226841, -0.28958324,  0.8038169 , -0.52108001, -0.72118601],
       [-0.54545667, -1.19204241, -0.91092677,  0.50279899,  0.00519626],
       [ 0.35412458, -0.52874943, -0.27218764, -0.26890927,  0.89397154],
       [ 0.75819627, -0.16377977,  0.65535218,  0.95241129,  2.0730288 ]])

### random.randint

Create one dimension array with random values

In [38]:
np.random.randint(1, 100)

56

In [39]:
np.random.randint(0, 3)

1

In [40]:
np.random.randint(1, 10, size=10)

array([6, 6, 6, 2, 9, 1, 7, 4, 2, 1])

In [41]:
import random

a = random.sample(range(100), 10)
print(a)

[14, 83, 78, 17, 21, 86, 72, 45, 99, 41]


In [42]:
type(a)

list

In [43]:
len(a)

10

In [44]:
suf_arr = np.arange(0, 10)

suf_arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [45]:
np.random.shuffle(suf_arr)

suf_arr

array([8, 1, 5, 4, 0, 2, 9, 3, 6, 7])

## Array Attributtes and Methods

Heres some method to build numpy with array attributes:
+ reshape
+ max 
+ min
+ argmax
+ argmin
+ shape
+ reshape
+ dtype

And here's all of the example process:

In [46]:
arr = np.arange(15)

arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [47]:
ran_arr = np.random.randint(0, 50, 10)

ran_arr

array([22, 26,  0, 38,  6, 25, 25, 35, 33, 15])

### max

Get highest value from an array

In [48]:
ran_arr = np.random.randint(0, 50, 10)

ran_arr.max()

47

### argmax

Get index of highest value from an array

In [49]:
ran_arr = np.random.randint(0, 50, 10)

ran_arr.argmax()

8

### min

Get minimum value from an array

In [50]:
ran_arr = np.random.randint(0, 50, 10)

ran_arr.min()

11

### argmin

Get index of minimum value from an array

In [51]:
ran_arr = np.random.randint(0, 50, 10)

ran_arr.argmin()

2

### shape

Get the number of array indexs

In [52]:
arr = np.arange(15)

arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [53]:
arr.shape

(15,)

In [54]:
arr.shape[0]

15

In [55]:
matrix = np.array(my_matrix)

matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [56]:
matrix.shape

(3, 3)

In [57]:
matrix.shape[1]

3

### reshape

Change the array dimension or set an array to become a matrix

In [58]:
arr = np.arange(15)

arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [59]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [60]:
arr.reshape(1, 15).shape

(1, 15)

In [61]:
arr.shape

(15,)

In [62]:
arr.reshape(5, 3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [63]:
arr.reshape(5, 3).shape

(5, 3)

In [64]:
arr.reshape(15, 1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14]])

In [65]:
arr.reshape(15,1).shape

(15, 1)

### dtype

Check the type of data type

In [66]:
arr.dtype

dtype('int64')

In [67]:
arr1 = np.array(['1', 'test', '5.0'])

In [68]:
arr1.dtype

dtype('<U4')

### Data Checking

How to work and check the array data

In [69]:
name = ['asu', 'kuda']
name_single = ['kodok']
name_update = 'bulu'

if(name[1] != 'asu'):
    name[0] = name_update
else:
    print('kosong')

In [70]:
print(name[0])

bulu


In [71]:
print(name_single[0])

kodok


In [72]:
len(name)

2

## Check Array and NumpyArray

Here's some example of array checking for decission making:

In [73]:
my_list = [1, 2, 3, 4, 5]
my_list_empty = []

arr = np.arange(15)
arr_empty = np.array([])

In [74]:
if my_list == []:
    print("true")
else:
    print("false")

false


In [75]:
if not my_list:
    print("true")
else:
    print("false")

false


In [76]:
if my_list_empty == []:
    print("true")
else:
    print("false")

true


In [81]:
if not my_list_empty:
    print("true")
else:
    print("false")

true


In [77]:
if arr == []:
    print("true")
else:
    print("false")

false


/home/rohwid/PyEnvironment/tf-1.15-all-package-py.3.6/lib/python3.6/site-packages/ipykernel_launcher.py:1: DeprecationWarning: elementwise comparison failed; this will raise an error in the future.
  """Entry point for launching an IPython kernel.


In [78]:
if arr_empty == []:
    print("true")
else:
    print("false")

false


/home/rohwid/PyEnvironment/tf-1.15-all-package-py.3.6/lib/python3.6/site-packages/ipykernel_launcher.py:1: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  """Entry point for launching an IPython kernel.


In [79]:
if arr.size == []:
    print("true")
else:
    print("false")

false


In [80]:
if arr_empty.size == 0:
    print("true")
else:
    print("false")

true
