# Numpy Operations

Start working with numpy operation

In [1]:
import numpy as np

arr = np.arange(1,6)

arr

array([1, 2, 3, 4, 5])

## Arithmetic

Arithmetic operation in numpy

In [2]:
arr + arr

array([ 2,  4,  6,  8, 10])

In [3]:
arr * arr

array([ 1,  4,  9, 16, 25])

In [4]:
arr - arr

array([0, 0, 0, 0, 0])

In [5]:
arr / arr

array([1., 1., 1., 1., 1.])

In [6]:
1 / arr

array([1.        , 0.5       , 0.33333333, 0.25      , 0.2       ])

In [7]:
arr ** 2

array([ 1,  4,  9, 16, 25])

In [8]:
arr ** 3

array([  1,   8,  27,  64, 125])

## Universal Array Function

Use some array function to operate numpy

In [9]:
np.sqrt(arr)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798])

In [10]:
np.exp(arr)

array([  2.71828183,   7.3890561 ,  20.08553692,  54.59815003,
       148.4131591 ])

In [11]:
np.max(arr)

5

In [12]:
np.sin(arr)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427])

In [13]:
np.log(arr)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791])

In [14]:
np.sum(arr)

15

# Average

In [15]:
arr = np.arange(25)
arr = arr.reshape(5, 5)

arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [16]:
np.average(arr)

12.0

In [17]:
np.average(arr, axis=0)

array([10., 11., 12., 13., 14.])

In [18]:
np.average(arr, axis=1)

array([ 2.,  7., 12., 17., 22.])