# Numpy Indexing and Selection

How to work with index in numpy and select it.

In [1]:
import numpy as np

In [2]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [3]:
arr[1] = 5

print(arr)

[ 0  5  2  3  4  5  6  7  8  9 10]


## Bracket Indexing and Selection

How to select values inside the array

In [4]:
arr = np.arange(0,11)

arr[10]

10

In [5]:
arr[1:5]

array([1, 2, 3, 4])

In [6]:
arr[0:5]

array([0, 1, 2, 3, 4])

## Broadcasting

How to assign values in to arrays

In [7]:
arr = np.arange(0,11)

arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [8]:
arr[0:5] = 100

arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [9]:
arr[0:5] = [100, 101, 102, 103, 104]

arr

array([100, 101, 102, 103, 104,   5,   6,   7,   8,   9,  10])

### Array Slicing

Slicing to get specific value and remove the unecessary.

In [10]:
arr = np.arange(0, 11)

arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [11]:
slice_of_arr = arr[0:6]

slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [12]:
slice_of_arr[:] = 99

slice_of_arr

array([99, 99, 99, 99, 99, 99])

### Copy Array

Copy and assign value to an array

In [13]:
arr = np.arange(0,11)

arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [14]:
arr_copy = arr.copy()
arr_copy

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

### Array concatrnate

Join or merge two arrays into one array.

In [15]:
a = [1, 2, 3, 4]
b = np.array([5, 6, 7, 8])
c = np.array([[1, 2], [3, 4]])
d = np.array([[5, 6]])

ab = np.concatenate((a, b), axis=None)

ab

array([1, 2, 3, 4, 5, 6, 7, 8])

Join a **number** to **an array**

In [16]:
a = [1, 2, 3, 4]
b = np.array([5, 6, 7, 8])
c = np.array([[1, 2], [3, 4]])
d = np.array([[5, 6]])

number_b = np.concatenate((99, b), axis=None)

number_b

array([99,  5,  6,  7,  8])

Join matrix **c** and **d** depends on **rows**

In [17]:
a = [1, 2, 3, 4]
b = np.array([5, 6, 7, 8])
c = np.array([[1, 2], [3, 4]])
d = np.array([[5, 6]])

c

array([[1, 2],
       [3, 4]])

In [18]:
d

array([[5, 6]])

In [19]:
cd = np.concatenate((c, d), axis=0)

cd

array([[1, 2],
       [3, 4],
       [5, 6]])

Join matrix **c** and transposed matrix **d** depends on ***column***

In [20]:
a = [1, 2, 3, 4]
b = np.array([5, 6, 7, 8])
c = np.array([[1, 2], [3, 4]])
d = np.array([[5, 6]])

cd = np.concatenate((c, d.T), axis=1)

cd

array([[1, 2, 5],
       [3, 4, 6]])

Join two array without axis

In [21]:
a = [1, 2, 3, 4]
b = np.array([5, 6, 7, 8])
c = np.array([[1, 2], [3, 4]])
d = np.array([[5, 6]])

ab = np.concatenate((a, b), axis=None)

ab

array([1, 2, 3, 4, 5, 6, 7, 8])

In [22]:
ab = np.concatenate((a, b))

ab

array([1, 2, 3, 4, 5, 6, 7, 8])

Joint all list or arrays become an array, must be include `axis=None` syntax

In [23]:
a = [1, 2, 3, 4]
b = np.array([5, 6, 7, 8])
c = np.array([[1, 2], [3, 4]])
d = np.array([[5, 6]])

# generalize all list or array as single row
abcd = np.concatenate((a, b, c, d), axis=None)

abcd

array([1, 2, 3, 4, 5, 6, 7, 8, 1, 2, 3, 4, 5, 6])

Concatenate arrays without axis parameters

In [24]:
a = [1, 2, 3, 4]
b = np.array([5, 6, 7, 8])
c = np.array([[1, 2], [3, 4]])
d = np.array([[5, 6]])
e = 22
f = 26

ab = np.concatenate(([a], [b]))

ab

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [25]:
ef = np.concatenate(([e], [f]))

ef

array([22, 26])

In [26]:
# it will be come to an error if "axis = 1"
ef = np.concatenate(([e], [f]), axis=0)

ef

array([22, 26])

In [27]:
a = [1, 2, 3, 4]
b = np.array([5, 6, 7, 8])
c = np.array([[1, 2], [3, 4]])
d = np.array([[5, 6]])
e = [22]
f = [26]

ef = np.concatenate(([e], [f]))

ef

array([[22],
       [26]])

In [28]:
ef_row = np.concatenate(([e], [f]), axis=0)

ef_row

array([[22],
       [26]])

In [29]:
ef_row.shape

(2, 1)

In [30]:
ef_col = np.concatenate(([e], [f]), axis=1)

ef_col

array([[22, 26]])

In [31]:
ef_col.shape

(1, 2)

## Indexing 2D array

Start to work in 2D array with numpy

In [32]:
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,45]))
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [33]:
arr_2d[1]

array([20, 25, 30])

In [34]:
arr_2d[1][0]

20

In [35]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [36]:
arr_2d[2]

array([35, 40, 45])

In [37]:
arr_2d[2,:]

array([35, 40, 45])

In [38]:
arr_2d[:,0]

array([ 5, 20, 35])

In [39]:
arr_2d[0,:]

array([ 5, 10, 15])

for loops while slicing

In [40]:
arr = np.arange(0, 6)

arr

array([0, 1, 2, 3, 4, 5])

In [41]:
for array in arr[1:]:
    print(array)

1
2
3
4
5


## Fancy Indexing

Little bit advancing the indexing and insert the values to it.

In [42]:
arr2d = np.zeros((10,10))

arr2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [43]:
arr_length = arr2d.shape[0]

arr_length

10

In [44]:
for i in range(arr_length):
    arr2d[i] = i
    
arr2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9., 9.]])

In [45]:
arr2d[[2,4,6,8]]

array([[2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.]])

In [46]:
arr2d[[6,4,2,7]]

array([[6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.]])

In [47]:
arr = np.zeros((10,10))

arr

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [48]:
len(arr)

10

In [49]:
arr.shape

(10, 10)

In [50]:
arr = np.zeros((10,10))

for i in range(arr.shape[0]):
    for j in range(arr.shape[1]):
        if j == i:
            arr[i][j] = 7
            arr[(arr.shape[0] - 1) - j][j] = 7

arr

array([[7., 0., 0., 0., 0., 0., 0., 0., 0., 7.],
       [0., 7., 0., 0., 0., 0., 0., 0., 7., 0.],
       [0., 0., 7., 0., 0., 0., 0., 7., 0., 0.],
       [0., 0., 0., 7., 0., 0., 7., 0., 0., 0.],
       [0., 0., 0., 0., 7., 7., 0., 0., 0., 0.],
       [0., 0., 0., 0., 7., 7., 0., 0., 0., 0.],
       [0., 0., 0., 7., 0., 0., 7., 0., 0., 0.],
       [0., 0., 7., 0., 0., 0., 0., 7., 0., 0.],
       [0., 7., 0., 0., 0., 0., 0., 0., 7., 0.],
       [7., 0., 0., 0., 0., 0., 0., 0., 0., 7.]])

In [51]:
arr = np.arange(100)
arr = arr.reshape(10, 10)

arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

Default looping in numpy is by row

In [52]:
for col in arr:
    print(col)
    break

[0 1 2 3 4 5 6 7 8 9]


How to loop by column in numpy

In [53]:
for col in arr.T:
    print(col)
    break

[ 0 10 20 30 40 50 60 70 80 90]


## Selection

Working with boolean selecton in numpy

In [54]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [55]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [56]:
bool_arr = arr > 4

bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [57]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [58]:
arr[arr > 2]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [59]:
x = 2

arr[arr > x]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [60]:
a = [1, 2]

len(a)

2